name: Github Action sharing - Greeting

on:
  push:

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        # run: echo 'Hello Github Action!'
        run: echo "${{ env.GREETING }} $FULL_NAME. Today is ${{ evn.DAY_OF_WEEK }}"
        env:
          FULL_NAME: 'Gary Huang'
    env:
      GREETING: Hello
env:
  DAY_OF_WEEK: Monday
